// Code generated by "esc -private -o=fs.go -modtime=1546544639 -pkg=schema -include=.*\.schema.json$ -ignore=test-fixtures/* ."; DO NOT EDIT.

package schema

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	if !f.isDir {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is not directory", f.name)
	}

	fis, ok := _escDirs[f.local]
	if !ok {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is directory, but we have no info about content of this dir, local=%s", f.name, f.local)
	}
	limit := count
	if count <= 0 || limit > len(fis) {
		limit = len(fis)
	}

	if len(fis) == 0 && count > 0 {
		return nil, io.EOF
	}

	return []os.FileInfo(fis[0:limit]), nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// _escFS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func _escFS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// _escDir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func _escDir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// _escFSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func _escFSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// _escFSMustByte is the same as _escFSByte, but panics if name is not present.
func _escFSMustByte(useLocal bool, name string) []byte {
	b, err := _escFSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// _escFSString is the string version of _escFSByte.
func _escFSString(useLocal bool, name string) (string, error) {
	b, err := _escFSByte(useLocal, name)
	return string(b), err
}

// _escFSMustString is the string version of _escFSMustByte.
func _escFSMustString(useLocal bool, name string) string {
	return string(_escFSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/namespace/batch-create-namespace.schema.json": {
		name:    "batch-create-namespace.schema.json",
		local:   "namespace/batch-create-namespace.schema.json",
		size:    1034,
		modtime: 1546544639,
		compressed: `
H4sIAAAAAAAC/8yTz26jQAyH7zzFaHaPIQNaErYc22tV9RUc4hJHmRnkcaVGEe9e8SdplADtsdefP3/Y
g3yKlFL6L211ofROpA6FMUICLmasKAgfl+RNKHdowTiwGGoo0WxAyl1cMoJgfIn1otf1+FlZGLMP3sV9
uvRcmS3Dm8RJPoj/DI01+xpZCIMuVDdam17012lbIEF7k01avsoH2OBhtNQ1gwiye511DOzylC6a6XqL
yLHG9h2CMLlKj4PNSNwsohmd3+yxlDvdfVP3eFO7fjPciI2x9s9kSaaUFj7IvltdqPR/lq3zLEvyf3ny
sFql63Q9upMlN7QkszuTE6yQfzJmEM9Q4a+bNJqZe/rfXoMXCpjheIY6cY9pITl0xGN7ouqpO1H1cnOi
tx9ros8AAAD//zgsSV4KBAAA
`,
	},

	"/namespace/batch-delete-namespace.schema.json": {
		name:    "batch-delete-namespace.schema.json",
		local:   "namespace/batch-delete-namespace.schema.json",
		size:    339,
		modtime: 1546544639,
		compressed: `
H4sIAAAAAAAC/2SPMW7DMAxFd51CYDtGYbcCHovOvQMjszaDWBIoLkbhuxeyY7dI1sfnZ/0f572HV+mh
8zCaldohmhiloDxINZ3PkrHGkSfCRBPXQpHxQhbH0PONjcOB4bTlNn1PdojXmlPY6DnrgL3St4W393v4
5f5h0VxYTbhC59enNXrk/9N2EOPpgTVsc+H272oqaYC/43Jyzxap0rxLizs0MLHbany0rf5z3eq/Hrbu
mXy5cjRwi/sNAAD//wW6edlTAQAA
`,
	},

	"/namespace/create-namespace.schema.json": {
		name:    "create-namespace.schema.json",
		local:   "namespace/create-namespace.schema.json",
		size:    674,
		modtime: 1546544639,
		compressed: `
H4sIAAAAAAAC/7ySy26zMBCF9zyF5f9fBgwqgZZtt1XVV3DIlEyELxpPpUYR715xCUmBdZc+PmfOp9Fc
IyGE/I9HWQl5YvahUoqRtY0JGgxMlwSdCvUJjFZWGwhe16BqAs0Qz4LcjYNG421YpdQ5OBuPauKoUUfS
nxyn5TTy3xT05DwQIwRZiQGqV1t9gPZRGayaGch+bCUmS3LNdt1K7n/44qGnC0xoG/nrv7u/ul20zrjD
GWq+ZWaL7JewYNyuuUcIvHtDg7zIGf2N5svISmTPeV6UeZ6WT2X6st9nRVY8Qhm0kzPdYkXL0ACtmwM7
0g38aXk0E0hGbgfP63BA4n1xQMtdd9FPAAAA///Uq161ogIAAA==
`,
	},

	"/namespace/delete-namespace.schema.json": {
		name:    "delete-namespace.schema.json",
		local:   "namespace/delete-namespace.schema.json",
		size:    266,
		modtime: 1546544639,
		compressed: `
H4sIAAAAAAAC/1yOsY6DMAyGd54i8t14wbedlPnmvkMKLgRBEtleUMW7VyFQpE6Rvvz+9D0bYwx8hx6c
gVE1i0PUoD5apiGI8tqGhNKNtHiMfiHJviPsaSYl+wbwU0V1eMoc4iQp2krbxAP27B9qf/8O5ddxmDll
Yg0k4MweVeilv2DhuuaCQJRDHOD42cq7VZ8GnffJ/x5qbh+hpyHdJ+oUmq15BQAA//+Y4RVRCgEAAA==
`,
	},

	"/": {
		name:  "/",
		local: `.`,
		isDir: true,
	},

	"/namespace": {
		name:  "namespace",
		local: `namespace`,
		isDir: true,
	},
}

var _escDirs = map[string][]os.FileInfo{

	".": {},

	"namespace": {
		_escData["/namespace/batch-create-namespace.schema.json"],
		_escData["/namespace/batch-delete-namespace.schema.json"],
		_escData["/namespace/create-namespace.schema.json"],
		_escData["/namespace/delete-namespace.schema.json"],
	},
}
